default_platform(:android)

platform :android do
  desc "내부 테스트 트랙으로 업로드"
  lane :internal_release do
    upload_to_play_store(
      track: 'internal',
      aab: 'Builds/Android/TileRunner.aab' # 유니티가 만든 AAB 파일 경로
    )
  end
end